// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfHjy260E-efjHrpnW1aZrc-eTkq3h2Rc',
    appId: '1:596258968971:web:5107c54e5fe098b41a8b8e',
    messagingSenderId: '596258968971',
    projectId: 'first-project-cd333',
    authDomain: 'first-project-cd333.firebaseapp.com',
    storageBucket: 'first-project-cd333.appspot.com',
    measurementId: 'G-EXZ9Y7MMRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGJuc6dYo5mvEwp7ldx-XLtcI1mTc2CM4',
    appId: '1:596258968971:android:0e49603689df312b1a8b8e',
    messagingSenderId: '596258968971',
    projectId: 'first-project-cd333',
    storageBucket: 'first-project-cd333.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Pr6Pni-FNcsvV1FDmg5xy8E0hTTJoFU',
    appId: '1:596258968971:ios:84ce7a606a91e8311a8b8e',
    messagingSenderId: '596258968971',
    projectId: 'first-project-cd333',
    storageBucket: 'first-project-cd333.appspot.com',
    iosBundleId: 'com.example.formFieldApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2Pr6Pni-FNcsvV1FDmg5xy8E0hTTJoFU',
    appId: '1:596258968971:ios:36d35fa7a67233901a8b8e',
    messagingSenderId: '596258968971',
    projectId: 'first-project-cd333',
    storageBucket: 'first-project-cd333.appspot.com',
    iosBundleId: 'com.example.formFieldApplication1.RunnerTests',
  );
}
